---
root: true

parser: babel-eslint

parserOptions:
    ecmaVersion: 6
    sourceType: module
    jsx: true

env:
    browser: true
    node: true
    jest: true

plugins:
    - react

extends:
    - eslint-config-airbnb
    - plugin:import/errors
    - plugin:import/warnings

rules:
    arrow-parens: ['error', 'as-needed', { requireForBlockBody: true }]
    arrow-body-style: 0
    indent: [error, 4, { SwitchCase: 1 }]
    linebreak-style: 0
    no-console: error
    no-debugger: error
    no-multi-spaces: 0
    no-nested-ternary: 0
    no-underscore-dangle: 0
    padded-blocks: 0
    prefer-destructuring: 0
    prefer-promise-reject-errors: 0
    space-before-function-paren: [error, { named: always, anonymous: always }]
    import/extensions: 0
    import/no-extraneous-dependencies: 0
    import/no-named-as-default: 0
    import/no-unresolved: 0
    import/default: 1
    import/namespace: 1
    jsx-a11y/anchor-is-valid: 0
    jsx-a11y/label-has-for: 0
    jsx-a11y/click-events-have-key-events: 0
    jsx-a11y/interactive-supports-focus: 0
    jsx-a11y/mouse-events-have-key-events: 0
    jsx-a11y/no-noninteractive-element-interactions: 0
    jsx-a11y/no-static-element-interactions: 0
    react/default-props-match-prop-types: 0
    react/jsx-closing-tag-location: 0
    react/jsx-filename-extension: 0
    react/jsx-indent: [error, 4]
    react/jsx-indent-props: [error, 4]
    react/jsx-max-props-per-line: [error, { maximum: 2, when: 'multiline' }]
    react/no-typos: 0
    react/no-unused-prop-types: 0
    react/prop-types: 0
    react/forbid-prop-types: [2, { "forbid": ["any"]}]
    react/require-default-props: 0
    react/no-array-index-key: 1

globals:
    Promise: true
    describe: true
    it: true